Initial release of amr detection pipeline
phac-nml/irida-plugin-amr-detection pull request #1
Opened 2019-04-18 14:25 UTC by apetkau

This implements the initial release of the AMR detection pipeline (implementing issue https://github.com/phac-nml/irida/issues/137).

In order to test this out you have to first start up a Galaxy instance and install the following tools:

* RGI <https://toolshed.g2.bx.psu.edu/view/card/rgi/715bc9aeef69>
* staramr <https://toolshed.g2.bx.psu.edu/view/nml/staramr/930893c83a1a>
* shovill <https://toolshed.g2.bx.psu.edu/view/iuc/shovill/865119fcb694>

Once you've got those tools installed, you will have to build the plugin. This first requires you to install IRIDA to your Maven repository:

```bash
# Run this in the irida project
cd irida

# Checkout specific version I compile against
git checkout 19.01.3
mvn clean install -DskipTests
```

Now, to build you can run:

```bash
# Run this in this code repository
cd irida-plugin-amr-detection

mvn clean package
```

Now, to install the plugin, you can run:

```bash
cp target/*.java /etc/irida/plugins
```

Now, start up IRIDA and you can run the **AMR Detection** pipeline.

2019-04-23 18:29 UTC, deepsidhu85 requested changes
Just a few minor things otherwise it looks and works great

2019-04-23 18:29 UTC, deepsidhu85 commented on README.md
> +# Building
It might be a good idea to add in the directories that the below commands are to be run in

2019-04-23 18:29 UTC, deepsidhu85 commented on README.md
> +Please download the provided `amr-detection-[version].jar` from the [releases][] page and copy to your `/etc/irida/plugins` directory.  Now you may start IRIDA and you should see the pipeline appear
It might be useful to mention that the version that the user downloads must be for IRIDA version that they have installed

2019-04-23 18:29 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/plugin/amrdetection/AMRDetectionUpdater.java
> +
Add a comment for what the method does

2019-04-23 18:29 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/plugin/amrdetection/AMRDetectionUpdater.java
> +
Same as above

2019-04-23 18:29 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/plugin/amrdetection/AMRDetectionUpdater.java
> +		final int BEST_HIT_ARO = 8;
Is this variable and the one below the token number? If so, it might be a good idea to either leave a comment or change the variable name to be more specific

2019-04-23 18:29 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/plugin/amrdetection/AMRDetectionUpdater.java
> +	public void update(Collection<Sample> samples, AnalysisSubmission analysis) throws PostProcessingException {
Add a comment for what this method does as well

2019-04-26 16:11 UTC, apetkau commented on README.md
> +# Building
Fixed in 94b24e28e5ab8b7955644360f9f1d5c3f5471c8f

2019-04-26 16:13 UTC, apetkau commented on README.md
> +Please download the provided `amr-detection-[version].jar` from the [releases][] page and copy to your `/etc/irida/plugins` directory.  Now you may start IRIDA and you should see the pipeline appear
These don't actually have to match up when installing the plugin, only when building the plugin. That is, you can build the plugin for IRIDA `19.01` and install in `19.04` and it should just work. The only place you'd run into trouble is if you are building the plugin (you need to make sure to install the specific version of IRIDA mentioned in the `pom.xml` file).

2019-04-26 16:13 UTC, apetkau commented on src/main/java/ca/corefacility/bioinformatics/irida/plugin/amrdetection/AMRDetectionUpdater.java
> +
Done in f3fe830430500e565123476db364e3534dcac993. I also did a bit of refactoring here to simplify some of the methods.

2019-04-26 16:14 UTC, apetkau commented on src/main/java/ca/corefacility/bioinformatics/irida/plugin/amrdetection/AMRDetectionUpdater.java
> +
Done in f3fe830430500e565123476db364e3534dcac993

2019-04-26 16:14 UTC, apetkau commented on src/main/java/ca/corefacility/bioinformatics/irida/plugin/amrdetection/AMRDetectionUpdater.java
> +		final int BEST_HIT_ARO = 8;
Yes, that is correct. I've named these variables to end with `_INDEX`  in f3fe830430500e565123476db364e3534dcac993.

2019-04-26 16:25 UTC, apetkau commented on src/main/java/ca/corefacility/bioinformatics/irida/plugin/amrdetection/AMRDetectionUpdater.java
> +	public void update(Collection<Sample> samples, AnalysisSubmission analysis) throws PostProcessingException {
In theory, this should inherit documentation from the interface in the IRIDA code <https://github.com/phac-nml/irida/blob/development/src/main/java/ca/corefacility/bioinformatics/irida/pipeline/results/updater/AnalysisSampleUpdater.java#L23>.

However, it looks like when we install the IRIDA packages we aren't including the sources. I've added an issue to include this (https://github.com/phac-nml/irida/issues/368), but this is something to fix in the main IRIDA codebase.

2019-04-26 17:18 UTC, deepsidhu85 commented on README.md
> +Please download the provided `amr-detection-[version].jar` from the [releases][] page and copy to your `/etc/irida/plugins` directory.  Now you may start IRIDA and you should see the pipeline appear
Oh ok. Makes sense!

2019-04-26 17:19 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/plugin/amrdetection/AMRDetectionUpdater.java
> +	public void update(Collection<Sample> samples, AnalysisSubmission analysis) throws PostProcessingException {
Awesome thanks

2019-04-26 17:22 UTC, merged